### ISSUE TITLE
Taxonomy Concepts Not Populating?

### ISSUE THREAD

**Issue by vbhayden** [cassproject/CASS#325]
Morning @Lomilar,

We're having some trouble with getting the taxonomy creation to work, namely the Concept portion.

Creating a taxonomy with a vanilla docker setup of CaSS will appear to create the Taxonomy, but populating any of the Concepts appears to fail due to not initially finding the concept schema.

> console.trace() undefined: error: EcRemotePostInner: http://localhost/api/data/schema.cassproject.org.0.4.skos.Concept/d13cbd1a-c455-4812-9764-3f4d85225c6d,,Error: Object not found or you did not supply sufficient permissions to access the object.

![cass-tax-issue](https://github.com/user-attachments/assets/dd575a6c-7547-44ce-8395-e634af8cd1b6)

The docker-compose used here:

```
version: '3'
services:
  cass:
    image: cassproject/cass:node-1.5.63
    restart: always
    networks:
      - public
    ports:
      - 80:80
    environment:
      - CASS_LOOPBACK=http://localhost/api/
      - ELASTICSEARCH_ENDPOINT=http://elasticsearch:9200
      - PORT=80
    ulimits:
      memlock:
        soft: -1
        hard: -1

  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - public

networks:
  public:
    driver: bridge

```
